name             'vagrant'
maintainer       'Tamas Molnar'
maintainer_email 'stiron@gmail.com'
license          'apache2'
description      'Installs/Configures vagrant'
long_description 'Installs/Configures vagrant'
version          '0.0.1'
